<a href="https://colab.research.google.com/github/chakravartulavinay/my_practice_notes/blob/main/vinaypractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x=-90
print(type(x))

<class 'int'>


In [ ]:
v=7j
print(type(v))

<class 'complex'>


In [ ]:
txt = "The best things in life are free!"
print("free" in txt)

True


In [ ]:
v="hello,world!"
print(v[-4:-2])
v.upper()

rl


'HELLO,WORLD!'

In [ ]:
age = 36
txt = "My name is John, I am " +str( age)
print(txt)

My name is John, I am 36


In [ ]:
print(" v \n i \n n \n a \n y \n")

 v 
 i 
 n 
 a 
 y 



In [ ]:
v= ' vinay is a good boy'
s='VINAY'
print(v.upper())
print(v.capitalize())
print(s.lower())
print(s.find('I'))
print(v.replace('o','v'))
print(v.strip())

 VINAY IS A GOOD BOY
 vinay is a good boy
vinay
1
 vinay is a gvvd bvy
vinay is a good boy


In [ ]:
v= "vinay"
print(v[:2])

vi


In [ ]:
print(bool('hello'))
print(bool('9'))

True
True


In [ ]:
print("v\ni\nn\na\ny")

v
i
n
a
y


In [ ]:
range(5)


range(0, 5)

In [ ]:
x='vinay '*4
print(x)

vinay vinay vinay vinay 


In [ ]:
x=['vinay','vijay','harsha']
for v in x:
  print(v)
  if v=='vijay':
    break

vinay
vijay


In [ ]:
v=['kALYANI','hema']
for x in v:
  if x=='hema':
    break
    print(x)

In [ ]:
for i in range(1,11):
  print(f"2x{i}={2*i}")


2x1=2
2x2=4
2x3=6
2x4=8
2x5=10
2x6=12
2x7=14
2x8=16
2x9=18
2x10=20


In [ ]:
for j in range(2,5):
  for i in range(1,11):
    print(j,"x",i,"=",j*i)
  print()



2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20

3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40



In [ ]:
for i in range(1,11):
  print('2 x',i,"=",2*i)


2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20


In [ ]:
def v(fruits)
for x in fruits:
  print(x)
  if x=='banana':
    break
    print(x)

SyntaxError: ignored

In [ ]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
     break
     print(x)



In [ ]:
for i in range(6):
  print(i)
else:
    print("finally finished")

In [ ]:
i=0
while i<6:
  print(i)
  i+=1



In [ ]:
i=0
while i<6:
  if i==5:
    print(i)
    break

  i+=1


In [ ]:
i=1
while i<=6:
  print(i)
  i+=1
else:
  print("i is no longer less than 6")

In [ ]:
x=0
for v in range(1,10,2):
  print(v)

In [ ]:
total = 0
for num in range(1,6):
  total+=num
  print(total)#look at the print stuff in the below code its bcoz identation matters


In [ ]:
total = 0
for num in range(1,6):
  total+=num
print(total)

In [ ]:
name = "john"
age=18
print("name:",name,"-","age:",age)

In [ ]:
name = input("enter your name")
print("hello",name,"I nice to meet you. ")

In [ ]:
age=input(" enter your age")
print(' in 10 years you will be ',int(age)+10,'years old')

In [ ]:
radius=float(input(" enter the radius "))
area = 3.14*radius**2
print(" the area of the circle ",area)

In [ ]:
for num in range(1,6):
  print(num/10)

In [ ]:
fruits = ['apple','banana','cherry']
for v in fruits:
 print(v,"i want to eAT")

In [ ]:
message = "hello,world!"
for char in message:
  print(char)

In [ ]:
for v in range(0,10,2):
  print(v)

In [ ]:
for i in range(3):
  for j in range(2):
    print(i,j)

In [ ]:
v=range(1,11)
sum=0
for x in v:
  sum+=x
print(sum)

In [ ]:
x=3.24555
print("value of x",format(x,".2f"))

In [ ]:
v=2.23344123
print("value of v",format(v,".2f"))

In [ ]:
help(format)

In [ ]:
v=int(input("enter the number "))
for x in range(1,11):
  if x==6 or x==7:
    print(v,"x",x,"=",v*x)
  continue
else:
    print("executing finished ")


In [ ]:
v=int(input("enter the value"))
i=0
while i<=10:
  i+=1
  if i==6:
    continue
  print(v,"x",i,"=",v*i)

In [ ]:
v=""
while v!="quit":
  v=input("enter the commanad")
  print("executing command "+(v))
else:
  print("executing finished")

In [ ]:
start = int(input("enter the number"))
ending=int(input(" enter the 2nd number "))
v=int(input("enter the skip number"))
for i in range(start,ending+1):
  for j in range(1,11):
    if v==i:
      continue
    else:
      print(i,"x",j,"=",i*j)
  print()

In [ ]:
help(print)

In [ ]:
v=int(input(range(1,3)))

#functions

In [ ]:
def v():#defining function
  print("hello world")

In [ ]:
c=0
def v():
  print("hello world")
  c=a*b
  print(c)
a=int(input("enter"))
b=int(input("enter"))
v()

In [ ]:
def v(fname="vinay",lname="kumar"):
  print("chakravartula",fname,lname)
v(lname="vinay",fname="kumar")
v("vijay","kumar")
v()

In [ ]:
def v(food):
  for x in food:
    if x=="karbuza":
      continue
    print(x)
fruits=["apple","cherry","karbuza"]
v(fruits)

In [ ]:
def v(x):
  pass
  print(5*x)
v(5)
v(10)

In [ ]:
def v():
  pass

In [ ]:
def v(s=range(1,10)):
     print(s)
v(range(2,4))
v()

In [ ]:
def v(name):
  message="hi!",name
  return message
v("harsha")


In [ ]:
def v(name):
  print("hi",name)
v('vinay')


In [ ]:
def v(fname,lname):
  s="chakravartula",fname,lname
  return s
full_name = v("vinay","kumar")
print(full_name)




In [ ]:
def v(num1,num2):
  sum=num1+num2
  return sum
result=v(54,46)
print(result)

In [ ]:
def v(num1,num2):
  sum=num1+num2
  print('the sum is: ',sum)
v(46,54)

In [ ]:
def v(*fruits):
  print(fruits[2])
v("apple","cherry","strawberry","banana")


In [ ]:
def my_function(**kid):
  print("His last name is " + kid["lname"])

my_function(fname = "Tobias", lname = "Refsnes")

In [ ]:
def v(*std):
  print("first rank goes to : ",std[3])
v("vinay","harsha","vijay","kalyani","harsha")


In [ ]:
def  v(**std):
  print("good student of the year:",std["worst"])
v(good="vinay",bad="harsha",worst="vijay")

In [ ]:
def v(num1,num2=6):
  add=num1+num2
  print("addition is:",add)
v(num2=7,num1=8)

In [ ]:
def v(name):
  print("hello!,",name)
  print(" the length of the name is :" , len(name))
v("vinay")


In [ ]:
def v():
  print("hello world!")
v()


In [ ]:
def concatenate_strings(*args):
    result = ""
    for string in args:
        result += string
    return result

concatenated_string = concatenate_strings("Hello", " ", "World", "!")
print("Concatenated string:", concatenated_string)

In [ ]:
def v(*args):
  sum=0
  for x in args:
    sum+=x
  print(" sum:",sum)
v(1,2,3,4,5,6,7,8,9,10)

In [ ]:
def v(num):
  sum=0
  for x in num:
    sum+=x
  print("sum:",sum)
t=num=[1,2,3,4,5,6,7,8,9,10]
v(t)

In [ ]:
# a code to display tables
def v(*args):
  for i in args:
    for j in range(1,11):
      print(i,"x",j,"=",i*j)
    print()
v(2,4)





In [ ]:
numbers=[1,2,3,4,6,67,78]
print("length:",len(numbers))
print("maximum:",max(numbers))
print("minimum:",min(numbers))

In [ ]:
import numpy as np
mean=np.mean(numbers)
median=np.median(numbers)
print(mean,median)

In [ ]:
import math as m
v=m.sqrt(12)
print(format(v,".2f"))

In [ ]:
import random as ran
ran.randint(1,10)

In [ ]:
import random as ran
v=ran.uniform(1,2)
print(format(v,".2f"))

In [ ]:
import statistics as stat ### note
stat.mean([1,2,3,4,5])

In [ ]:
b = "Hello, World!"
print(b[:5])

In [ ]:
b = "Hello, World!"
print(b[:-1])

Problem 2: Average of Even Numbers Implement a function average_of_evens() that takes a list of integer numbers and returns the average of all even numbers in the list.The function should return 0 if there are no even numbers in the list.

In [ ]:
def average_of_evens(num):
  sum=0
  number=0
  average=0
  for x in num:
    if x%2==0:
      sum+=x
      number+=1
  average=sum/number
  print(f"the average of evens in the list:{average}")
num=[1,2,3,4,5]
average_of_evens(num)

# list

In [ ]:
v=[1,"vinay",2,'vijay',3,'kalyani',4,'vinay']
print(v)
print(len(v))
print(type(v))
print(id(v))

In [ ]:
# access the elements
v=[1,'vinay',2,'vijay',3,'kalyani',4,'vinay']
a=v[1]
print(a)
a=v[1:6]
print(a)
c=v[::-1]
print(c)
a=v[-1]
print(a)
x=v[-4:]
print(x)
v.index(3)

In [ ]:
v=[1,'vinay',2,'vijay',3,'kalyani',4,'vinay']
print('vinay' not in v)
if 'vinay' not in v:
  print('yes')

In [ ]:
# mmodifying lists
v=[1,'vinay',2,'vijay',3,'kalyani',4,'vinay']
v[1]='harsha'
print(v)
v[1:]=[2]
print(v)
v[1:2]=[2,'vinay',3,'vijay',4,'kalyani']
print(v)

In [ ]:
v=[1,'vinay',2,'vijay',3,'kalyani',4,'vinay']
v.insert(2,"vinay")
print(v)
v.append(2)
print(v)
v.append('vinay')
print(v)
h=[1,2,3,4,5]
v.extend(h)
print(v)
h.extend(v)
print(h)
list3=v+h
print(list3)

In [ ]:
#removing elements in a list
v=[1,'vinay',2,'vijay',3,'kalyani',4,'vinay']
del v[1]
v.append('vinay')
print(v)
v.remove(2)
print(v)
v.pop(1)
print(v)
v.clear()
print(v)

In [ ]:
#
v=[1,'vinay',2,'vijay',3,'kalyani']
for x in v:
  print(v)
for t in v:
  print(t)


In [ ]:
thislist = ["apple", "banana", "cherry"]
for i in range(len(v)):
  print(v[i])

In [ ]:
#list comprehension
v=[1,'vinay',2,'vijay',3,'kalyani']
for x in v:
  print(x)
[print(x) for x in v]

In [ ]:
v=['vinay','vijay','kalyani','kuw']
n=[]
for i in v:
  if 'a' not in i:
     n.append(i)
print(n)

In [ ]:
v=['vinay','vijay','kalyani','kuw']
n=[]
n=[i for i  in v if 'a' not in i]
print(n)

In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)

In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
# newlist = [expression for item in iterable if condition == True] syntax for comprehension list
newlist = [x for x in fruits if "a" in x]

print(newlist)

In [ ]:
v=[x for x in range(10)]
print(v)

In [ ]:
v=[x for x in range(10) if x>5]
print(v)

In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
v=[x.upper() for x in fruits]
print(v)

In [ ]:
v=[x for x in range(10)]
print(v)


In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
v=[x.upper() for x in fruits]
print(v)

In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
for x in fruits:
    if 'a' in x:
      print(x)


In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
[x for x in fruits if 'a' in x]

In [ ]:
# sorting lists
v=['vinay','Vijay','kalyani']
v.sort()
print(v)

In [ ]:
s=[100, 50, 65, 82, 23]
s.sort(reverse=True)
print(s)
s.reverse()
print(s)

In [ ]:
v.sort(key=str.upper)
print(v)

In [ ]:
v= [100, 50, 65, 82, 23]
n=v.copy()
print(n)

In [ ]:
#joining lists
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
v=['vinay','Vijay','kalyani']
n=fruits+v
print(n)
fruits.extend(v)
print(fruits)

In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
v=['vinay','Vijay','kalyani']


In [ ]:
v=[1,'vinay',2,'vijay',3,'kalyani']
n=v[1:6:2]
print(n)

In [ ]:
v=[1,'vinay',2,'vijay',3,'kalyani']
n=v*3
print(n)

In [ ]:
v=[1,2,3,4,5]
[i**2 for i in v if i%2!=0]

In [ ]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
[i.upper() for i in fruits]

In [ ]:
v=[1,2,3,4,5]
n=min(v)#accesing min value in the list
print(n)
s=max(v)
print(s)
v.index(4)

In [ ]:
v=list(input(" enter the valuess"))
print(list(v))

In [ ]:
v=[]
while True:
  s=input('enter a value')
  if s=='quit':
    break
  v.append(s)
print(v)

In [ ]:
user_input = []
while True:
  s=input("enter the values")
  if s=='quit':
    break
  user_input.append(s)
print(user_input)

2# Tuples

In [ ]:
v=(1,2,3,'vinay','kumar')
print(type(v))
print(len(v))

In [ ]:
z=list(v)
z[1]='vinay'
v=tuple(z)
print(v)

In [ ]:
v=(1,2,3,'vinay','kumar')
y=list(v)
y.append('chakravartula')
v=tuple(y)
print(v)

In [ ]:
v=(1,2,3,'vinay','kumar')
a,b,c,d,e = v
print(a,b,c,d,e)

In [ ]:
v=(1,2,3,'vinay','kumar',2,3,4)
a,*b,c=v
print(a,b,c)

In [ ]:
v=('vinay','kumar','vijay','vijay')
[x.upper() for x in v ]

In [ ]:
# strings
v="hello vinay welcome to python"
print(len(v))
v.replace('o','v')

# sets

In [ ]:
v={1,2,3,4,5}
print(v)

In [ ]:
v={1,2,3,4,5,'vinay','kumar'}
v.add('kalyani')
print(v)

In [ ]:
v={1,2,3,4,5,'vinay','kumar'}
h={'harsha','vijay'}
v.update(h)
print(v)

In [ ]:
v={1,2,3,4,5,'vinay','kumar'}
v.clear()
print(v)

In [ ]:
v={1,2,3}
h={3,5,4}
h.symmetric_difference(v)
n=v-h
print(n)

In [ ]:
v=[1,2,2,2,2,3,4,5]
print(list(set(v)))

# dictionaries

In [ ]:
d={"name":"vinay","roll no":203,"section":"c","good boy":True,"colors":["red","green"]}
print(d)
print(d["colors"])

In [ ]:
d = {"brand": "Ford","model": "Mustang","year": 1964}
x=d["brand"]
print(x)
print(d["brand"])
print(d["model"])
x=d.get("model")
print(x)
d.keys()
d["color"]=["red","blue"]
print(d)
d.values()
d.items()
print("model" in d)

In [ ]:
d = {"brand": "Ford","model": "Mustang","year": 1964}
d.update({"year":2000})
print(d)

In [ ]:
d = {"brand": "Ford","model": "Mustang","year": 1964}
d["year"]=2000
print(d)

In [ ]:
d = {"brand": "Ford","model": "Mustang","year": 1964}
del d["model"]
print(d)

In [ ]:
d = {"brand": "Ford","model": "Mustang","year": 1964}
for x in d:
  print(x)
for x in d:
  print(d[x])

In [ ]:
d = {"brand": "Ford","model": "Mustang","year": 1964}
d.items()

In [ ]:
d = {"brand": "Ford","model": "Mustang","year": 1964}
for x in d.items():
  print(x)

In [ ]:
d = {"brand": "Ford","model": "Mustang","year": 1964}
for x,y in d.items():
  print(x)
  print(y)

In [ ]:
myfamily = {"child1" : {"name" : "Emil","year" : 2004 },"child2" : {"name" : "Tobias","year" : 2007},"child3" : {"name" : "Linus","year" : 2011}}

In [ ]:
myfamily = {
  "child1" : {
    "name" : "Emil",
    "year" : 2004
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2007
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}

In [ ]:
child1 = {
  "name" : "Emil",
  "year" : 2004
}
child2 = {
  "name" : "Tobias",
  "year" : 2007
}
child3 = {
  "name" : "Linus",
  "year" : 2011
}

myfamily = {
  "child1" : child1,
  "child2" : child2,
  "child3" : child3
}
print(myfamily["child2"]["year"])

In [ ]:
import json
person = {
 "name": "John",
 "age": 25,
 "address": {
     "street": "123 Main St",
     "city": "New York"
 }
}
# Converting dictionary to JSON string
json_data = json.dumps(person)
print(json_data)
# Converting JSON string to dictionary
# person_dict = json.loads(json_data)
# print(person_dict["name"])  # Output: "John"

In [ ]:
d = {"brand": "Ford","model": "Mustang","year": 1964}
import json
j=json.dumps(d)
print(j)

In [ ]:
v={"name","age",'city'}
t={"vinay",21,"hyderabad"}
d=dict(zip(v,t))#zipping
print(d)

In [ ]:
d = {"brand": "Ford","model": "Mustang","year": 1964}
list1=list(d.keys())
print(list1)
print(list(d.values()))

# numerical python--numpy
## NumPy is a Python library.NumPy is used for working with arrays

In [ ]:
import numpy as np
print(np.__version__)# version of numpy.
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
print(id(arr))

In [ ]:
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))
print(id(arr))

In [ ]:
arr=np.array(42)##0-D array
print(arr)

In [ ]:
arr=np.array([1,2,3,4,5])##1-D array
# print(arr)
v=np.array([[1,2,3],[4,5,6]])##2-D array
# print(v)
s=np.array([[[1,2,3],[4,5,6],[2,3,4],[5,6,7]]])#3-D array
# print(s)
print(arr.ndim)
print(v.ndim)
print(s.ndim)

# accesing numpy array

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[-1])#1-D array accesing
print(arr[1]*arr[2])

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])#2-D arrays
print(" 2nd element on 1st row",arr[0,1])
print("5th element on 2nd row",arr[1,4])

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])

# slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])#slicing of 1-D array
print(arr[2::2])
print(arr[4:])

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])#slicing of 2-D array
print(arr[1,1:5])
print(arr[0:2,1:4])

# numpy datatypes

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)
arr=np.array([1,2,3])
print(arr.dtype)

In [ ]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
arr=np.array([1.1,2.2,3.3])
newaee=arr.astype('i')
print(newaee)
print(newaee.dtype)

In [ ]:
arr=np.array([1,0,3])
newarr=arr.astype('b')
print(newarr)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()## copying a numpy array
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()##viewing an array
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
arr=np.array([1,2,3,4,5])
x=arr.view()
x[0]=9
print(arr)
print(x)

In [ ]:
arr=np.array([1,2,3,4,4])
x=arr.view()## if array owns the data than it will return none
y=arr.copy()
print(x.base)
print(y.base)
print(arr.shape)

#shape of numpy array


In [ ]:
arr=np.array([[1,2,3,4,0],[5,6,7,8,9],[1,2,3,4,5]])
print("shape of array",arr.shape)

#reshaping numpy arrays

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)
newarr=arr.reshape(4,3)
print(arr.reshape(4,3).base)
print(newarr)

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

#iterating a numpy array

In [ ]:
arr=np.array([1,2,3,4,5])
[print(x) for x in arr]

1
2
3
4
5


[None, None, None, None, None]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
[print(x) for x in arr]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])#2-D array
for x in arr:
  for y in x:
    print(y)

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr):## same result obtained as above but in different method
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for  x in np.ndenumerate(arr):
  print(x)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((1, 3), 8)


# numpy array joining

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)##joining arrays using concatenate function
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr=np.stack((arr1,arr2),axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([[1, 2, 3],[1,2,4],[6,7,8]])
arr2 = np.array([[4, 5, 6],[2,3,4],[78,90,78]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[ 1  2  3]
 [ 1  2  4]
 [ 6  7  8]
 [ 4  5  6]
 [ 2  3  4]
 [78 90 78]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr=np.hstack((arr1,arr2))## using hstack axis1
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2, 3],[4,5,6],[7,8,9]])
arr2 = np.array([[4, 5, 6],[5,6,4],[34,55,45]])
arr=np.hstack((arr1,arr2))
print(arr)

[[ 1  2  3  4  5  6]
 [ 4  5  6  5  6  4]
 [ 7  8  9 34 55 45]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr=np.vstack((arr1,arr2))#vstacking axis0
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([[1, 2, 3],[5,6,7],[7,8,9]])
arr2 = np.array([[4, 5, 6],[4,5,6],[90,6,5]])#dstackinhg
# v=np.hstack((arr1,arr2))
# print(v)
arr=np.dstack((arr1,arr2))
print(arr)

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 5  4]
  [ 6  5]
  [ 7  6]]

 [[ 7 90]
  [ 8  6]
  [ 9  5]]]


# splitting of arrays

In [ ]:
arr=np.array([1,2,3,3,4,4,5])
newarr=np.array_split(arr,4)
print(newarr)
newarr[0]##accessing splitted array

[array([1, 2]), array([3, 3]), array([4, 4]), array([5])]


array([1, 2])

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])##splitting of 2-D arrays
newarr=np.array_split(arr,6)
print(newarr)
# accesssing 5th array
newarr[4]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr=np.array_split(arr,3)
print(newarr)
newarr[0][1][2]##accessing elements of a specified array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
new=np.vsplit(arr,3)
print(new)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr=np.hsplit(arr,3) ## hsplit is used to get the ouput as below
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# array searching in numpy
## in numpy searching we weill only get indexes as ouput

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
newarr=np.where(arr==4)
print(newarr)## ouput will gives the indexes where 4 is present

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
newarr=np.where(arr%2==0)
print(newarr)# ouput will gives the indexes where condition is satisfied by the numbers

(array([1, 3, 5, 6]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
newarr=np.searchsorted(arr,5)## in this method first it will sort the array and than it will gives the indexes as output
print(newarr)

7


In [ ]:
arr=np.array([7,8,3,4,5,6,9,2,3,1,5,6])
print(len(arr))
x=np.searchsorted(arr,3)
print(x)

In [ ]:
arr = np.array([6,7,8,9])
newarr=np.searchsorted(arr,7,side='right')## searchsorting from right side
print(newarr)
newarr=np.searchsorted(arr,7,side='left')# searchsorting from left side
print(newarr)

In [ ]:
arr=np.array([1,6,7,8,3,5])
newarr=np.searchsorted(arr,[2,3,5,6])### this will returns the indexes where the mention valued can be placed
print(newarr)

[1 1 1 1]


# numpy array sorting

In [ ]:
arr=np.array([6,3,4,6,7,7,1,2,7])
# print(np.sort(arr))## sortinag

None


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1],[5,32,4]])
print(np.sort(arr))##sorting 2-D arrays

# filtering numpy arrays

In [ ]:
arr=np.array([3,4,5,62,3,4,5])
print(len(arr))
x=[False,True,False,True,True,False,False]##acceessing elements using boolean values
newarr=arr[x]##mandatory
print(newarr)

In [ ]:
##example
# Create a filter array that will return only values higher than 42
arr=np.array([41,44,45,46,67,34,67,56])
print(len(arr))
filter_array=[]
for x in arr:
  if x>42:
    filter_array.append(x)
print(filter_array)

In [ ]:
# Create a filter array that will return only even elements from the original array
arr=np.array([41,44,45,46,67,34,67,56])
print(len(arr))
filter_array=[]
for x in arr:
  if x%2==0:
    filter_array.append(x)
print(filter_array)

8
[44, 46, 34, 56]


In [ ]:
arr=np.array([41,44,45,46,67,34,67,56])
filter_array=arr>42
new_arr=arr[filter_array]## filtering without using for loop
print(new_arr)

[44 45 46 67 67 56]


In [ ]:
v=[]
v.append((input("enter the cvalues")))
print(list(v))
print(np.sort(v))

enter the cvalues123445
['123445']
['123445']


In [ ]:
arr=np.array([[6,4,9],[8,9,9],[7,9,9]])
product=np.dot(arr,arr)## matrixmutiplication by using dot operator
print(product)
r=arr@arr##shortcut for matrix multiplication
print(r)

In [ ]:
arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
arr.reshape(-1)## converting 2-D unto 1-D


In [ ]:
data = np.array(
    [[1, 200, 3, 4, 17],
      [166, 4, 30, 4, 5],
      [71, 20, 6, 4, 12],
      [61, 9, 3, 9, 5],
      [1050, 20, 9, 4, 1000],
      [1050, 20, 9, 9, 1000] ]
                )
print(data)
print(data.shape)
np.mean(data,axis=0)

[[   1  200    3    4   17]
 [ 166    4   30    4    5]
 [  71   20    6    4   12]
 [  61    9    3    9    5]
 [1050   20    9    4 1000]
 [1050   20    9    9 1000]]
(6, 5)


array([399.83333333,  45.5       ,  10.        ,   5.66666667,
       339.83333333])

In [ ]:
data = np.array(
    [[1, 200, 3, 4, 17],
      [166, 4, 30, 4, 5],
      [71, 20, 6, 4, 12],
      [61, 9, 3, 0, 5],
      [1050, 20, 9, 4, 1000],
     [1770, 120, 29, 45, 9000]]
                )
# print(np.mean(data))
# print(np.mean(data,axis=1))
# print(np.mean(data,axis=0))
print(np.max(data))
print(np.max(data,axis=0))
print(np.max(data,axis=1))

9000
[1770  200   30   45 9000]
[ 200  166   71   61 1050 9000]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 4])
v=arr1<arr2
new=arr1[v]
print(new)

[1 3]


In [ ]:
arr=np.random.rand(3,4)
print(arr)

In [ ]:
print(np.max(arr,axis=0))

5


In [ ]:
print(np.max(arr,axis=1))

In [ ]:
v=np.array([[1,2,3],[7,8,9]])
n=np.array([[7,6,3],[2,3,2]])
# arr=np.vstack((v,n))
# print(arr)
# arr=np.hstack((v,n))
# print(arr)
arr=np.dstack((v,n))
print(arr)
print(arr.ndim)

[[[1 7]
  [2 6]
  [3 3]]

 [[7 2]
  [8 3]
  [9 2]]]
3


In [ ]:
import numpy as np
arr3d=np.random.rand(4,3,4)## last two values represents rows and columns where first value represent no of sets we want
print(arr3d)
print(type(arr3d))

[[[0.84777457 0.12638233 0.74746398 0.16754363]
  [0.03211295 0.53178773 0.20862375 0.72245443]
  [0.39117879 0.07439833 0.56092889 0.30811877]]

 [[0.99114705 0.28650899 0.65456897 0.66818979]
  [0.64682861 0.29525193 0.10903199 0.07328793]
  [0.23397628 0.09783843 0.13201397 0.48711838]]

 [[0.34247368 0.65396591 0.44553837 0.45403216]
  [0.98411961 0.93776674 0.86850306 0.48764992]
  [0.77777837 0.47351109 0.54057251 0.69840508]]

 [[0.10013252 0.80663413 0.14326294 0.21855692]
  [0.24128492 0.02316    0.42260517 0.32295455]
  [0.28703067 0.13395996 0.16319299 0.75200835]]]
<class 'numpy.ndarray'>


In [ ]:
print(arr3d.shape)
v=np.max(arr3d)
print(v.shape)
t=np.max(arr3d,axis=0)#it will compare fisrt element with other matrices(i.e submatrices in 3-D array) first elemenet and than prints maximum value
print(t.shape)
print(t)
s=np.max(arr3d,axis=1)#it will give maximum of a paticular matrix column in 3-D array and vice versa
print(s.shape)
print(s)
n=np.max(arr3d,axis=2)#it will compare fisrt row and than displays maximum value and vice versa.
print(n.shape)
print(n)

NameError: ignored

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.reshape(3,2))##reshaping
print(arr.transpose())## transposing
print(arr.shape)
print(arr.T)## second method for transposing mostly used in programming

In [ ]:
#flatten
flat=arr.reshape(6)
print(flat)
print(flat.shape)
flat1=arr.reshape(-1)## different value and result is same
print(flat1)## different
print(flat.shape)

In [ ]:
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.exp(arr))

In [ ]:
import numpy as np
arr=np.array([[[1,2],
               [3,4]],
              [[2,3],
               [4,5]]])
print(arr)
print("\n",np.sum(arr,axis=0))##summing a 3-D using axis
print("\n",np.sum(arr,axis=1))
print('\n',np.sum(arr,axis=2))

[[[1 2]
  [3 4]]

 [[2 3]
  [4 5]]]

 [[3 5]
 [7 9]]

 [[4 6]
 [6 8]]

 [[3 7]
 [5 9]]
